server:
  port: 8095
spring:
  application:
    name: springboot-kafka-bdd
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
    producer:
      acks: all
