server:
  port: 8095
spring:
  application:
    name: springboot-kafka-bdd
  main:
    banner-mode: "off"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: spring-kafka-acceptance-test-example-consumer
      enable-auto-commit: true
      auto-offset-reset: latest
  jackson:
    deserialization:
      fail-on-unknown-properties: false
    visibility:
      FIELD: any
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_empty
